color: blue
fieldLayouts:
  2da5d12a-27aa-47cf-9e2d-82eaa5cc1941:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 99556d89-aa1d-4598-bfe5-3406409405f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7dc2f8b-e835-4083-be86-da4196ba1cc7 # Adresa
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 895cc57f-1be8-46fd-885c-80a83f54f660
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2662638-d03b-426d-806d-f1bc364f9976 # Střed mapy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed27eead-90b5-4656-b322-6daa6f359128
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f2803cad-4ede-4ac3-b703-7f94e05a80ee # Typ mapy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0043581-d2c1-4a26-8cf3-24c2f0f22484
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 085b6ccc-e756-49b0-98d5-8465fc922c5e # Zoom mapy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5638437b-1519-4558-98f5-0a3a27c4b1d2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 56744c48-6008-42a2-9d41-369577d0fcb0 # Škála
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c1f7502-5133-476e-82e6-08b2db9cf1ee
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 484a087c-7def-44c2-8b23-f6fd2a8d19fa # Šířka obrázku
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4990b136-199d-4c0f-a018-9d317a494f8f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 37ee958a-03e5-4dc6-aafb-27baf62b070a # Výška obrázku
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a6ff69b-7adc-4f23-b49f-712da1ea5258
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d89093c3-d898-45bf-abd7-d3dc4f5d7d6f # Dodatečné parametry mapy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f94c778e-c369-4a79-8d6f-2cd8d9061e49
            userCondition: null
            warning: null
            width: 100
        name: Obsah
        uid: 5137b914-4ff3-4eb8-9fb8-637b8e8650b8
        userCondition: null
handle: addressWithMap
hasTitleField: false
icon: map
name: 'Adresa s mapou'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
