columnSuffix: null
handle: address
instructions: null
name: Adresa
searchable: false
settings:
  maxAddresses: 1
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
