columnSuffix: null
handle: image
instructions: null
name: Obrázek
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:8f83d1d4-e049-488d-8597-4072043c6aa5' # Obrázky
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:8f83d1d4-e049-488d-8597-4072043c6aa5' # Obrázky
  restrictedLocationSubpath: null
  selectionLabel: 'Nový obrázek'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:8f83d1d4-e049-488d-8597-4072043c6aa5' # Obrázky
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
