columnSuffix: null
handle: zoom
instructions: null
name: 'Zoom mapy'
searchable: false
settings:
  decimals: 0
  defaultValue: 14
  max: 20
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
