dateModified: 1720725457
email:
  fromEmail: ondrej.tuma@gmail.com
  fromName: therapy11
  transportType: craft\mail\transportadapters\Sendmail
fs:
  icons:
    hasUrls: true
    name: Ikony
    settings:
      path: '@webroot/uploads/icons'
    type: craft\fs\Local
    url: '@web/uploads/icons'
  images:
    hasUrls: true
    name: Obrázky
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    0bff3dc7-a35c-4963-9d2b-3e662ef7a40c: 'Public Schema' # Public Schema
    2a6fe1a3-cd1a-4c31-a444-23edd44e1854: Nabídka # Nabídka
    6a6ed4eb-db13-43fe-baef-64a63ddfe7cc: Nabídka # Nabídka
    6c05ceaf-146d-4c06-8ed9-678874010683: Obrázek # Obrázek
    8e38523c-8645-47e2-a452-7ae0566cb2fe: Délka # Délka
    8f83d1d4-e049-488d-8597-4072043c6aa5: Obrázky # Obrázky
    9b5ff481-39a6-4f42-852a-ebe777a51140: 'Hlavní stránka' # Hlavní stránka
    9b6ee81b-2961-4bbb-a07b-1be86d2c8eae: 'Statická část citace' # Statická část citace
    10a47349-5326-45b4-a1d5-40d006c3af3b: 'Text odkazu' # Text odkazu
    11b72eaa-13ab-4652-b1ac-ee26f8ed667e: Homepage # Homepage
    15be827f-6fb0-4093-9f21-426515701f11: Ikona # Ikona
    29efb6fe-023a-4fa0-9f60-3c079b5b2ad4: Citát # Citát
    88fd3ef7-9c27-48f5-b416-02379fef30ad: therapy11 # therapy11
    91c8e751-385d-46ee-9a3b-3bc063894418: Ikony # Ikony
    97fa92a8-2f52-4634-b119-e2a6dadab8a6: 'Dynamická část citace' # Dynamická část citace
    166fbe0f-b2e0-4feb-8839-d20b74e92a40: Citát # Citát
    636f748c-03aa-4eab-ba15-0ef768dd16c9: 'Dlaždice Za kolik?' # Dlaždice Za kolik?
    959d9d91-83bf-4fa7-810d-674000bfe314: 'Dlaždice Kdy?' # Dlaždice Kdy?
    4008b991-c333-4dad-a38e-519a7e854209: Cena # Cena
    76127beb-52d6-4453-910c-f3dad6d6bd96: 'Dlaždice S Kým?' # Dlaždice S Kým?
    2315827a-6f20-4607-9064-9f8bf9e79aef: 'Dlaždice Jak?' # Dlaždice Jak?
    13609346-d613-4f7a-a7c7-f57c1a3e72ab: Podnadpis # Podnadpis
    44933892-f53c-4c7d-bbea-e71825f13d8f: Jméno # Jméno
    a4335c86-c4fe-4f0c-bea4-b57a8d428987: 'Dlaždice Jak?' # Dlaždice Jak?
    b08ccd31-4315-4ac1-a20c-88aca89bc22f: 'Dlaždice S Kým?' # Dlaždice S Kým?
    b4844c8a-2fb2-4b5e-9ddf-30e2e5db8d2a: 'Dlaždice Kdy?' # Dlaždice Kdy?
    c6cb9019-eab6-45ec-b794-ed112f9baab1: 'Dlaždice Za kolik?' # Dlaždice Za kolik?
    c7dc2f8b-e835-4083-be86-da4196ba1cc7: Adresa # Adresa
    cfc99793-b745-4cc3-b356-7f6983d898d4: therapy11 # therapy11
    dbab4a88-65ea-4b4f-b377-f9731d5a367a: Autor # Autor
    e53fcdee-b4a2-4984-bc20-60b69acfba24: Popis # Popis
    f2f30657-7666-42af-a6ec-912c0c7ae954: 'Dlaždice Co?' # Dlaždice Co?
    f3ab0cf2-537f-472b-837e-ea65dd45f0a8: 'Dlaždice Co?' # Dlaždice Co?
system:
  edition: solo
  live: true
  name: 'Terapie 11'
  retryDuration: null
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
